[package]
name = "tetrust"
version = "0.1.0"
authors = ["Htet Aung Shine <h@shine.rocks>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
rand = "0.7.3"